name: Julian Jimsa
description: games and other stuff
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl:
domain_name: "https://julianjimsa.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Julian Jimsa"

# Disqus config
disqus-shortname: ""
